### ISSUE TITLE
SPAKE: different w values for different groups

### ISSUE THREAD

**Issue by greghudson** [npmccallum/ietf#22]
While working on test vectors I noticed that the w value we produce from the long-term key will be similar for different groups, except in length.  We generally try to avoid directly using the same keying material in multiple algorithms, so we should do something about that.

Once we have converted from OIDs to numbers for the group identifier, we should append the OID to the PRF+ pepper (currently just "SPAKEsecret").

**Comment by npmccallum** [comment]
Resolved in ba8291f.
