### ISSUE TITLE
SPAKE: for second optimization, KDC must supply etype-info2

### ISSUE THREAD

**Issue by greghudson** [npmccallum/ietf#39]
In the optimizations section, the second optimization is described as follows:

    Second, clients MAY skip the first pass and send an AS-REQ with a    
    PA-SPAKE PA-DATA element using the support choice. KDCs MUST support    
    this optimization.

In this case, the client is able to do optimistic preauth without knowing the initial reply key because SPAKESupport does not require that knowledge.  But the client will need to know the initial reply key in the next step.  Therefore, the KDC must send an ETYPE-INFO2 padata element with its KDC_ERR_MORE_PREAUTH_DATA_REQUIRED message, which is not an obvious product of the KDC implementation.  We need text specifying this requirement.  (It is already implemented in MIT krb5 1.14.)

**Comment by npmccallum** [comment]
Resolved in ba8291f.
