### ISSUE TITLE
SPAKE: include group number and enctype number in K'[n] derivation

### ISSUE THREAD

**Issue by greghudson** [npmccallum/ietf#40]
Our K'[n] derivation uses the concatenation of the following as the PRF+ input string:

* The fixed string "SPAKEKey"
* The SPAKE result K, serialized
* The transcript checksum
* The KDC-REQ-BODY encoding for the request
* The value n as a big-endian four-byte unsigned binary number

We are not including the length of each fields, instead relying on the fact that each field has a fixed length or a self-describing length to prevent input string collisions (meaning, cases where the PRF+ input string is the same even though the tuple of input parameters is different).

The serialized K value and the transcript checksum are only fixed-length once the group number and initial reply key enctype are determined.  By including those parameters as the second and third elements, we can guarantee that each tuple encodes to a different PRF+ input string.

**Comment by npmccallum** [comment]
Resolved in ba8291f.
